name: 'Download artifact from a github build'
description: 'Download artifact from a github build'
author: 'Benjamin Day Consulting, Inc.'
inputs:
  token:
    required: true
    description: 'token for accessing github api'
    default: 'default'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'database'
  color: 'blue'
