name: 'build-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
      - 'releases/*'
env:
  ACTIONS_RUNNER_DEBUG: true
  # MYGITHUBTOKEN: '${{ github.token }}'
  MYGITHUBTOKEN: '${{ secrets.GITHUB_TOKEN }}'
  # MYGITHUBTOKEN: '${{ env.ACTIONS_RUNTIME_TOKEN }}'  
  DEBUG: 'axios'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: print environment vars
        run: env
      - name: Inspect contexts
        run: |
          echo ""
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo ""
          echo "The job context is:"
          echo "${{ toJson(job) }}"
          echo ""
          echo "The steps context is:"
          echo "${{ toJson(steps) }}"
          echo ""
          echo "The runner context is:"
          echo "${{ toJson(runner) }}"
          echo ""
          echo "The strategy context is:"
          echo "${{ toJson(strategy) }}"
          echo ""
          echo "The matrix context is:"
          echo "${{ toJson(matrix) }}"
          echo ""
      - uses: actions/checkout@v2
      - name: run an ls -l
        run: ls -lR
        working-directory: '${{ github.workspace }}'
      - uses: ./
        with:
          # token: '${{ github.token }}'
          token: '${{ env.ACTIONS_RUNTIME_TOKEN }}'

        
